
stages:
  - build
  - release

services:
  - docker:19.03.1-dind
image: docker:19.03.1


build:
  stage: build
  script:
    - ./newartifacts
    - docker build -t registry.gitlab.com/grase/demo-docker/dev:latest .
    - docker push registry.gitlab.com/grase/demo-docker/dev:latest
