version: "3.0"

services:
  grasedemo:
    build: .
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.services.grase-demo-3.loadbalancer.server.port=80"
      - "traefik.http.routers.grase-demo-3.rule=Host(`demo.grasehotspot.org`)"
      - "traefik.http.routers.grase-demo-3.entrypoints=websecure"
      - "traefik.http.routers.grase-demo-3.tls=true"
      - "traefik.http.routers.grase-demo-3.tls.certresolver=default"
      - "whiteitsolutions.type=grase-demo"

networks:
    web:
        external: true
