version: "3.6"

services:
  grasedemo:
    #build: .
    image: registry.gitlab.com/grase/demo-docker:symfony4
    restart: always
    networks:
      - web
      - grasedb
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:devdemo.grasehotspot.org"
      - "traefik.port=80"
      - "whiteitsolutions.type=grase-demo"
    depends_on:
       - mysql

  mysql:
    image: mariadb
    networks:
      - grasedb
    volumes:
      - ./db_initial:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpw
      - MYSQL_DATABASE=radius
      - MYSQL_USER=grase
      - MYSQL_PASSWORD=grase
    healthcheck:
      test: ["CMD", "echo 'SELECT version();'| mysql"]
      timeout: 60s
      retries: 10


networks:
    grasedb:
    web:
        external: true
