#!/bin/bash
# Stop all running containers with that image
CID=$(docker ps -a | grep grasehotspot/demo:latest | awk '{ print $1}')
docker kill $CID >/dev/null 2>&1
docker rm $CID >/dev/null 2>&1

# Build new image
docker build -t grasehotspot/demo:latest .

# Cleanup dangling images
docker rmi $(docker images -f "dangling=true" -q)

./new_container
