#!/bin/bash

# Start Apache webserver
/etc/init.d/apache2 start

# MySQL container may take some time to start, so wait until we can connect to it
echo "Waiting for MySQL container to start"
sleep 2
for try in $(seq 1 30)
do
  echo Try $try
  mysql -h mysql -u grase -pgrase -e"quit" && break
  sleep 5
done

# Run database migrations, settings validations, demo data
/usr/share/grase/symfony4/bin/console doctrine:migrations:migrate --no-interaction
/usr/share/grase/symfony4/bin/console grase:settings-validate
/usr/share/grase/symfony4/bin/console grase:demo

# Warmup the cache
/usr/share/grase/symfony4/bin/console cache:warmup
chown www-data -R /usr/share/grase/symfony4/var/log
echo "Entering sleep loop. Webserver should be running"
sleep infinity
